# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    - name: s3Sync
  # You may pin to the exact commit or the version.
  # uses: Morr0/s3Sync@40e60183a9d3e2b4e366e0b942d3f92b9604ae74
      uses: Morr0/s3Sync@v.0.1
      with:
    # AWS Access ID
       accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # AWS SECRET Key
       secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # AWS Region
       region: ${{ secrets.region }}
    # AWS Bucket name
       bucket: ${{ secrets.bucket }}
    # Directory of github to sync, use '.' for the entire repository
       dir: ${{ secrets.dir }}
